### ISSUE TITLE
Zabbix plugin and graph support

### ISSUE THREAD

**Issue by ricco386** [erigones/ludolph-zabbix#1]
Zabbix plugin should support obtaining graphs via Zabbix API. It should have the following synopsis:

graph [@period]

keyword is a regular expression or pattern, which matches the graph for specific host/hostgroup.
period represents time period, e.g 1h will show data for the last hour.

Some interesting URLs:
https://www.zabbix.com/documentation/2.2/manual/api/reference/graph/get
https://github.com/sorah/hubot-zabbix/blob/master/scripts/hubot-zabbix.coffee

**Comment by dn0** [comment]
How should the graphs be rendered?

**Comment by dn0** [comment]
This could be implemented by showing the user links to particular graphs, but this would create a dependency on URL in the zabbix-fronted.
Closing for now because there is no demand for this.
