### ISSUE TITLE
Add configurable message type

### ISSUE THREAD

**Issue by ksyz** [erigones/ludolph-zabbix#3]
Receiving alerts from zabbix may be more use comfortable, when used in chat, instead of single message. Please, provide configurable [message type](https://tools.ietf.org/html/rfc3921#section-2.1.1) option.

[message type patch](https://github.com/erigones/ludolph-zabbix/files/59443/messagetype.txt)

**Comment by dn0** [comment]
This makes sense. The commit 8736808 makes it possible to change the message type via a POST parameter - `mtype`.
